name: "mosaico-testing"
services:
  mosaico-pg-testing:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mosaico
    ports:
      - "6543:5432"
    volumes:
      - mosaico-testing-pg-data:/var/lib/postgresql/data
    networks:
      - mosaico-testing
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "db_prod"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s


volumes:
  mosaico-testing-pg-data:

networks:
  mosaico-testing:
    name: mosaico-testing


