blank_issues_enabled: false
contact_links:
  - name: Features, Bug Reports, Questions
    url: https://github.com/mosaico-labs/mosaico/discussions/new/choose
    about: The starting point if you have any questions or suggestions about configuration, features or behavior.
