name: ci

on:
  push:
    branches:
      - "main"
    paths:
      - '**.rs'
      - '**.py'
      - '**/Cargo.toml'
      - '**/Cargo.lock'
      - '**/pyproject.toml'
      - '**/poetry.lock'
  pull_request:
    branches:
      - "main"
    paths:
      - '**.rs'
      - '**.py'
      - '**/Cargo.toml'
      - '**/Cargo.lock'
      - '**/pyproject.toml'
      - '**/poetry.lock'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  backend-linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Setup Rust Toolchain
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: stable

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2.8.2
        with:
          workspaces: "mosaicod -> target"
          cache-targets: true
          cache-on-failure: true

      - name: Run Linter
        run: |
          cd mosaicod
          cargo lint

  backend-unit-tests:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: mosaico
        ports:
          - 6543:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    env:
      DATABASE_URL: postgresql://postgres:password@localhost:6543/mosaico
      MOSAICO_REPOSITORY_DB_URL: postgresql://postgres:password@localhost:6543/mosaico
      SQLX_OFFLINE: true
      RUST_BACKTRACE: 1
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Setup Rust Toolchain
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: stable

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2.8.2
        with:
          workspaces: "mosaicod -> target"
          cache-targets: true
          cache-on-failure: true

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libpq-dev

      - name: Run Unit Tests
        run: |
          cd mosaicod
          cargo test

  python-sdk-unit-tests:
    runs-on: ubuntu-latest
    env:
      PYTHON_KEYRING_BACKEND: keyring.backends.null.Keyring
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Setup Python
        uses: actions/setup-python@v6.1.0
        with:
          python-version: '3.13'

      - name: Install Poetry
        run: pipx install poetry

      - name: Install Dependencies
        run: |
          cd mosaico-sdk-py
          poetry install

      - name: Run Unit Tests
        run: |
          cd mosaico-sdk-py
          poetry run pytest ./src/testing -k unit

  integration-tests:
    runs-on: ubuntu-latest
    needs: [backend-linter, backend-unit-tests, python-sdk-unit-tests]
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: mosaico
        ports:
          - 6543:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    env:
      PYTHON_KEYRING_BACKEND: keyring.backends.null.Keyring
      DATABASE_URL: postgresql://postgres:password@localhost:6543/mosaico
      MOSAICO_REPOSITORY_DB_URL: postgresql://postgres:password@localhost:6543/mosaico
      SQLX_OFFLINE: true
      RUST_BACKTRACE: 1
      RUST_LOG: mosaico=trace
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Setup Rust Toolchain
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: stable

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2.8.2
        with:
          workspaces: "mosaicod -> target"
          cache-targets: true
          cache-on-failure: true

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libpq-dev

      - name: Setup Python
        uses: actions/setup-python@v6.1.0
        with:
          python-version: '3.13'

      - name: Install Poetry
        run: pipx install poetry

      - name: Install Python Dependencies
        run: |
          cd mosaico-sdk-py
          poetry install

      - name: Build mosaicod
        run: |
          cd mosaicod
          cargo build

      - name: Run Integration Tests
        run: |
          mkdir -p /tmp/__mosaico_auto_testing__
          cd mosaicod
          ./target/debug/mosaicod run --port 6276 --local-store /tmp/__mosaico_auto_testing__ > /tmp/mosaicod_e2e_testing.out 2>&1 &
          MOSAICOD_PID=$!
          echo "Started mosaicod with PID: $MOSAICOD_PID"
          sleep 5
          cd ../mosaico-sdk-py
          poetry run pytest ./src/testing -k integration
          kill $MOSAICOD_PID 2>/dev/null || true
